name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: windows-latest
    steps:
      - name: Hello world
        id: beef
        run:
          echo "::set-output name=clock::noodle"
      - name: marco
        run:
          echo "${{steps.beef.clock}}"
  
