name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: windows-latest
    steps:
      - name: Hello world
        id: beef
        run:
          echo "{clock}={noodle}" >> $env:GITHUB_OUTPUT;
      - name: marco
        run:
          echo "${{steps.beef.clock}}";
  
